# Generated by Django 4.0.5 on 2022-06-22 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdfreader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantrecord',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfreader.state'),
        ),
    ]
