# Generated by Django 4.0.5 on 2022-06-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfreader', '0002_alter_applicantrecord_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantrecord',
            name='state',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
